### ISSUE TITLE
How to add API key

### ISSUE THREAD

**Issue by oleteacher** [MaxyMoos/mistral-vscode#1]
Love to see this working, have real use for this in a classroom test.

Cannot figure out how to set API key? 

![image](https://github.com/user-attachments/assets/830a1b8a-4ffe-41dd-9347-875a018d832d)

**Comment by oleteacher** [comment]
Looks like project is dead.

**Comment by MaxyMoos** [comment]
Project is indeed dead as I moved away from using VS Code (plus it was just a toy project).

I have updated the code nonetheless and released a v0.0.4 to allow using current Mistral models and I think in the way I may have solved that settings issue by changing the publisher name for the extension in order to satisfy new VS Code requirements.

Cheers
